### ISSUE TITLE
Download theme does not create ~/.cache/hotdoc/themes/

### ISSUE THREAD

**Issue by thiblahute** [hotdoc/hotdoc#119]
```
Traceback (most recent call last):
  File "/home/meh/devel/hotdoc/hotdoc/hotdoc/run_hotdoc.py", line 304, in execute_command
    app.parse_config(config)
  File "/home/meh/devel/hotdoc/hotdoc/hotdoc/run_hotdoc.py", line 91, in parse_config
    self.project.parse_config(self.config, toplevel=True)
  File "/home/meh/devel/hotdoc/hotdoc/hotdoc/core/project.py", line 327, in parse_config
    extension.parse_toplevel_config(config)
  File "/home/meh/devel/hotdoc/hotdoc/hotdoc/core/extension.py", line 204, in parse_toplevel_config
    self.formatter.parse_toplevel_config(config)
  File "/home/meh/devel/hotdoc/hotdoc/hotdoc/core/formatter.py", line 1049, in parse_toplevel_config
    html_theme = self.__download_theme(uri)
  File "/home/meh/devel/hotdoc/hotdoc/hotdoc/core/formatter.py", line 1014, in __download_theme
    urlretrieve(uri.geturl(), tarball, _download_progress_cb)
  File "/usr/lib64/python3.4/urllib/request.py", line 196, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/meh/.cache/hotdoc/themes/hotdoc
```

**Comment by thiblahute** [comment]
That must be fixed as it works on the CI server, closing.
