### ISSUE TITLE
0.8.101 has a broken submodule reference

### ISSUE THREAD

**Issue by sarum9in** [hotdoc/hotdoc#138]
Steps to reproduce:

```shell
$ git clone https://github.com/hotdoc/hotdoc.git
$ cd hotdoc/
$ git checkout 0.8.101
$ git submodule init
Submodule 'cmark' (https://github.com/MathieuDuponchelle/cmark.git) registered for path 'cmark'
Submodule 'hotdoc/extensions/syntax_highlighting/prism' (https://github.com/PrismJS/prism.git) registered for path 'hotdoc/extensions/syntax_highlighting/prism'
Submodule 'hotdoc/hotdoc_bootstrap_theme' (https://github.com/hotdoc/hotdoc_bootstrap_theme.git) registered for path 'hotdoc/hotdoc_bootstrap_theme'
$ git submodule update
Cloning into '/tmp/tmp.TlurWRL6Xy/hotdoc/cmark'...
Cloning into '/tmp/tmp.TlurWRL6Xy/hotdoc/hotdoc/extensions/syntax_highlighting/prism'...
Cloning into '/tmp/tmp.TlurWRL6Xy/hotdoc/hotdoc/hotdoc_bootstrap_theme'...
error: Server does not allow request for unadvertised object 040fca843a1f62a1007b6c8d883aab19cc83efda
Fetched in submodule path 'cmark', but it did not contain 040fca843a1f62a1007b6c8d883aab19cc83efda. Direct fetching of that commit failed.
```

**Comment by sarum9in** [comment]
Well I am using a standard documentation, just tried to reproduce with git tools. See example below:

```shell
$ git clone https://github.com/hotdoc/hotdoc.git
$ cd hotdoc/
$ git checkout 0.8.101
$ python3 setup.py install --prefix=/usr --root=/tmp/hotdoc-blabla
checking out submodules for the first time
Submodule 'cmark' (https://github.com/MathieuDuponchelle/cmark.git) registered for path 'cmark'
Submodule 'hotdoc/extensions/syntax_highlighting/prism' (https://github.com/PrismJS/prism.git) registered for path 'hotdoc/extensions/syntax_highlighting/prism'
Submodule 'hotdoc/hotdoc_bootstrap_theme' (https://github.com/hotdoc/hotdoc_bootstrap_theme.git) registered for path 'hotdoc/hotdoc_bootstrap_theme'
Cloning into '/tmp/tmp.TlurWRL6Xy/hotdoc/cmark'...
Cloning into '/tmp/tmp.TlurWRL6Xy/hotdoc/hotdoc/extensions/syntax_highlighting/prism'...
Cloning into '/tmp/tmp.TlurWRL6Xy/hotdoc/hotdoc/hotdoc_bootstrap_theme'...
error: Server does not allow request for unadvertised object 040fca843a1f62a1007b6c8d883aab19cc83efda
Fetched in submodule path 'cmark', but it did not contain 040fca843a1f62a1007b6c8d883aab19cc83efda. Direct fetching of that commit failed.
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    require_clean_submodules(SOURCE_DIR, ['cmark'])
  File "/tmp/tmp.TlurWRL6Xy/hotdoc/hotdoc/utils/setup_utils.py", line 112, in require_clean_submodules
    _update_submodules(repo_root)
  File "/tmp/tmp.TlurWRL6Xy/hotdoc/hotdoc/utils/setup_utils.py", line 80, in _update_submodules
    "git submodule update --recursive", cwd=repo_dir, shell=True)
  File "/usr/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git submodule update --recursive' returned non-zero exit status 1.
```

Is this the right way to do it?

**Comment by MathieuDuponchelle** [comment]
yes, thanks, let me try to reproduce then

**Comment by sarum9in** [comment]
Now it works just fine, thank you.

**Comment by MathieuDuponchelle** [comment]
no problem :)
