### ISSUE TITLE
All extensions become disabled after libgda valadoc is installed

### ISSUE THREAD

**Issue by lantw44** [hotdoc/hotdoc#176]
If you install [libgda](https://gitlab.gnome.org/GNOME/libgda) with documentation enabled, you can no longer use hotdoc because all extensions become disabled.
```
$ hotdoc --list-extensions
Extensions:
```

The reason is that hotdoc can't parse `Gda-6.0.devhelp2` file installed by libgda. Hotdoc assumes a signal always has '#' included in its link. It is probably true for documents generated by gtk-doc, but it may not be true if it is generated by a different program. In this case, these files are generated by valadoc. This is the line which causes hotdoc to fail.
```xml
<keyword type="signal" name="Gda.Batch.changed" link="Gda.Batch.changed.html"/>
```

gi-extension crashes while reading the file.
```
$ python3 -c 'from hotdoc.extensions.gi.gi_extension import GIExtension'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lantw44/gnome/source/hotdoc/hotdoc/extensions/gi/gi_extension.py", line 53, in <module>
    from hotdoc.extensions.gi.gtkdoc_links import GTKDOC_HREFS
  File "/home/lantw44/gnome/source/hotdoc/hotdoc/extensions/gi/gtkdoc_links.py", line 110, in <module>
    gather_gtk_doc_links()
  File "/home/lantw44/gnome/source/hotdoc/hotdoc/extensions/gi/gtkdoc_links.py", line 103, in gather_gtk_doc_links
    if not parse_devhelp_index(dir_):
  File "/home/lantw44/gnome/source/hotdoc/hotdoc/extensions/gi/gtkdoc_links.py", line 45, in parse_devhelp_index
    anchor = link.split('#', 1)[1]
IndexError: list index out of range
```
I attached the file here in case you don't want to install or generate it yourself. [Gda-6.0.devhelp2](https://github.com/hotdoc/hotdoc/files/3376112/Gda-6.0.devhelp2.txt)

**Comment by MathieuDuponchelle** [comment]
Thanks for your report :) There were two issues at hand, the actual parsing error
