### ISSUE TITLE
Traceback when including markdown from a GtkDoc comment with a broken GtkDoc style link

### ISSUE THREAD

**Issue by thiblahute** [hotdoc/hotdoc#193]
Here is a test case: https://github.com/thiblahute/test_hotdoc/commit/988422346cdfd94540cc534834e469b485bb87da

And this is the traceback:

```
hotdoc run     
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
Traceback (most recent call last):
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/run_hotdoc.py", line 298, in execute_command
    res = app.run()
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/run_hotdoc.py", line 113, in run
    self.project.format(self.link_resolver, self.output)
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/project.py", line 198, in format
    self.tree.format(link_resolver, output, self.extensions)
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/tree.py", line 636, in format
    self.format_page(page, link_resolver, output, extensions)
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/tree.py", line 621, in format_page
    extension.format_page(page, link_resolver, output)
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/extensions/gi/gi_extension.py", line 199, in format_page
    Extension.format_page(self, page, link_resolver, output)
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/extension.py", line 682, in format_page
    page.format(self.formatter, link_resolver, actual_output)
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/tree.py", line 320, in format
    self.__format_content(formatter, link_resolver)
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/tree.py", line 304, in __format_content
    self.__format_page_comment(formatter, link_resolver)
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/tree.py", line 271, in __format_page_comment
    self.formatted_contents += formatter.format_comment(
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/formatter.py", line 249, in format_comment
    return self._format_comment(comment, link_resolver)
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/extensions/gi/formatter.py", line 298, in _format_comment
    ast = self._docstring_formatter.comment_to_ast(
  File "/home/thiblahute/devel/hotdoc/hotdoc/hotdoc/parsers/gtk_doc.py", line 453, in comment_to_ast
    while line[i] == ' ':
IndexError: string index out of range
```

**Comment by MathieuDuponchelle** [comment]
This is fixed
