### ISSUE TITLE
ValueError: AST node column range (0, 22) for line range (-1, 17) is not valid

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#252]
Trying to build `gst-doc` which is failing in my F37 toolbox container:

```
cassidy@toolbox ~/dev/gst/gstreamer  (main)$ ninja -C build gst-doc
ninja: Entering directory `build'
[2/2] Generating subprojects/gst-docs/GStreamer-doc with a custom command
FAILED: subprojects/gst-docs/GStreamer-doc 
/usr/local/bin/meson --internal hotdoc /usr/local/bin/hotdoc run --conf-file GStreamer-doc.json --builddir /var/home/cassidy/dev/gst/gstreamer/build/subprojects/gst-docs
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/wheezy/template/engine.py", line 55, in get_template
    return self.templates[name]
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'gi_flags.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/run_hotdoc.py", line 294, in execute_command
    app.run()
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/run_hotdoc.py", line 107, in run
    self.project.setup()
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/core/project.py", line 186, in setup
    self.tree.build(sitemap, self.extensions)
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/core/tree.py", line 489, in build
    self.project.add_subproject(name, source_file)
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/core/project.py", line 233, in add_subproject
    proj.setup()
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/core/project.py", line 183, in setup
    extension.setup()
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/extensions/gi/gi_extension.py", line 190, in setup
    self.__scan_sources()
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/extensions/gi/gi_extension.py", line 954, in __scan_sources
    self.__scan_node(root)
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/extensions/gi/gi_extension.py", line 949, in __scan_node
    self.__scan_node(cnode)
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/extensions/gi/gi_extension.py", line 949, in __scan_node
    self.__scan_node(cnode)
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/extensions/gi/gi_extension.py", line 924, in __scan_node
    self.__create_structure(GIClassSymbol, node, gi_name)
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/extensions/gi/gi_extension.py", line 816, in __create_structure
    self.__scan_node(cnode, parent_name=parent_name)
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/extensions/gi/gi_extension.py", line 930, in __scan_node
    self.__create_property_symbol(node, parent_name)
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/extensions/gi/gi_extension.py", line 702, in __create_property_symbol
    extra_content = self.formatter._format_flags(flags)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.11/site-packages/hotdoc/extensions/gi/formatter.py", line 92, in _format_flags
    template = self.engine.get_template('gi_flags.html')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wheezy/template/engine.py", line 57, in get_template
    self.compile_template(name)
  File "/usr/local/lib/python3.11/site-packages/wheezy/template/engine.py", line 110, in compile_template
    render_template = self.compiler.compile_source(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wheezy/template/compiler.py", line 27, in compile_source
    compiled = compile(node, name, "exec")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: AST node column range (0, 22) for line range (-1, 17) is not valid
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
ninja: build stopped: subcommand failed.

```

**Comment by thiblahute** [comment]
Could that be because of py 3.11 somehow?

**Comment by MathieuDuponchelle** [comment]
Hopefully we shouldn't have to worry about that scary second exception, what's your `wheezy.template` version @gdesmott ooc ? On my end it's `3.0.3`

**Comment by gdesmott** [comment]
`3.1.0` here

**Comment by MathieuDuponchelle** [comment]
Annoying, I can't reproduce with `3.1.0` either, as @thiblahute said possibly 3.11-related then?
