### ISSUE TITLE
Hotdoc is unnable to find extensions

### ISSUE THREAD

**Issue by pgarciasancho** [hotdoc/hotdoc#286]
I'm using Ubuntu 22.04. I've followed all the steps to install hotdoc in https://hotdoc.github.io/installing.html and no problems at all. However, when I try to inspect extensions, none are found:
```
> hotdoc --list-extensions
Extensions:

```
I've also tried this in Focal and Noble docker images, and same result. I've made sure that `HOTDOC_BUILD_C_EXTENSION` is enabled. Also, the virtual environment is working as expected and there are no conflicts with previously installed hotdoc files:
```
> which hotdoc     
/.../hotdoc_env/bin/hotdoc
```

**Comment by MathieuDuponchelle** [comment]
That's interesting, perhaps run with `HOTDOC_DEBUG=2` in the environment?

**Comment by pgarciasancho** [comment]
Thanks @MathieuDuponchelle, it reveals the error:
```
> hotdoc --list-extensions
DEBUG: [logging]: Verbosity set to 2
INFO: [[Errno 2] No such file or directory: 'clang']: Failed to load EntryPoint(name='get_extension_classes', value='hotdoc.extensions:get_extension_classes', group='hotdoc.extensions')
DEBUG: [core]: Traceback (most recent call last):
  File "/hotdoc_env/lib/python3.8/site-packages/hotdoc-0.17-py3.8-linux-x86_64.egg/hotdoc/utils/utils.py", line 158, in __load_entry_point
    classes = activation_function()
  File "/hotdoc_env/lib/python3.8/site-packages/hotdoc-0.17-py3.8-linux-x86_64.egg/hotdoc/extensions/__init__.py", line 56, in get_extension_classes
    from hotdoc.extensions.c.c_extension import CExtension
  File "/hotdoc_env/lib/python3.8/site-packages/hotdoc-0.17-py3.8-linux-x86_64.egg/hotdoc/extensions/c/c_extension.py", line 110, in <module>
    CLANG_HEADERS = get_clang_headers()
  File "/hotdoc_env/lib/python3.8/site-packages/hotdoc-0.17-py3.8-linux-x86_64.egg/hotdoc/extensions/c/c_extension.py", line 87, in get_clang_headers
    resource_dir = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'clang'
```

After installing `clang`: 
```
> apt-get install clang
(...)

> hotdoc --list-extensions
DEBUG: [logging]: Verbosity set to 2
Extensions:
 - c-extension 
 - check-missing-since-markers 
 - comment-on-github 
 - core-tags 
 - dbus-extension 
 - devhelp-extension 
 - edit-on-github 
 - gi-extension 
 - git-upload 
 - gst-extension 
 - license-extension 
 - search 
 - syntax-highlighting-extension 
```

It seems that installing libclang-dev as dewcribed in the [instructions](https://hotdoc.github.io/installing.html) is not enough.

**Comment by MathieuDuponchelle** [comment]
Ah annoying, but thanks for following up, care to make a patch and update the instructions?

**Comment by pgarciasancho** [comment]
Associated PR: https://github.com/hotdoc/hotdoc/pull/287
