### ISSUE TITLE
Not very helpful traceback if you forget to set output in the conf

### ISSUE THREAD

**Issue by thiblahute** [hotdoc/hotdoc#42]
Getting

```
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
Traceback (most recent call last):
  File "/usr/bin/hotdoc", line 31, in <module>
    doc_tool.format()
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tool.py", line 458, in format
    self.__setup_folder(self.output)
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tool.py", line 594, in __setup_folder
    if os.path.exists (folder):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

It could be nicely expained instead :)

**Comment by MathieuDuponchelle** [comment]
Yes.

I want to have a session where I work exclusively on the errors / warning interface in hotdoc, and that will be included in there. For now the error reporting is traceback-based, deal with it :P

**Comment by thiblahute** [comment]
Sure, but starting to list them will make it simpler to fix once it is the time :)

**Comment by MathieuDuponchelle** [comment]
You can now actually run hotdoc without specifying an output, which will do a "dry-run", helpful for prototyping clang arguments for example, closing thanks :)
