### ISSUE TITLE
Inconsistency in the way markdown paths are specify

### ISSUE THREAD

**Issue by thiblahute** [hotdoc/hotdoc#43]
We need to have something like

```  
"index": "markdown/index.markdown",
"gi_index": "transcoder-index.markdown"
```

but all my markdown are in `markdown/`

Otherwise, I am getting: 

```
[ptv] ➜  transcoder git:(master) ✗ hotdoc run --conf-file hotdoc.json
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
Traceback (most recent call last):
  File "/usr/bin/hotdoc", line 30, in <module>
    doc_tool.setup(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tool.py", line 428, in setup
    self.__setup(args)
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tool.py", line 555, in __setup
    self.parse_config(wizard.config)
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tool.py", line 644, in parse_config
    self.doc_tree.build_tree(self.index_file)
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tree.py", line 330, in build_tree
    page = self.page_parser.parse(source_file)
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tree.py", line 211, in parse
    self.check_links(page, ast)
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tree.py", line 171, in check_links
    self.check_links (page, c, node)
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tree.py", line 169, in check_links
    self.check_links (page, c, node)
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tree.py", line 146, in check_links
    subpage, subfolder = handler(self.doc_tree)
  File "/usr/lib/python2.7/site-packages/hotdoc_gi_extension/gi_extension.py", line 1299, in gi_index_handler
    new_page = doc_tree.build_tree(index_path, 'gi-extension')
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tree.py", line 331, in build_tree
    page.extension_name = extension_name
AttributeError: 'NoneType' object has no attribute 'extension_name'
```

**Comment by MathieuDuponchelle** [comment]
Yes, for now markdown paths are prefixed with the dirname of the "main index", to allow you to say

```
[my_subpage](my_subpage.markdown)
```

The correct solution to this will be to reimplement "markdown include directories", makes sense ?

**Comment by thiblahute** [comment]
> The correct solution to this will be to reimplement "markdown include directories", makes sense ?

:+1:
