### ISSUE TITLE
Exception in `hotdoc conf`

### ISSUE THREAD

**Issue by ptomato** [hotdoc/hotdoc#87]
As suggested in the documentation, I replaced my `hotdoc run` invocation with `hotdoc conf` to create a configuration file:
```
hotdoc --index api/index.md --output api/built --sitemap api/sitemap.txt conf
```
That throws an exception. I can also reproduce the same exception just by running `hotdoc conf` in an empty directory:
```
$ hotdoc conf
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
Traceback (most recent call last):
  File "/home/philip/checkout/hotdoc/hotdoc/run_hotdoc.py", line 39, in run
    doc_repo.load_command_line(args)
  File "/home/philip/checkout/hotdoc/hotdoc/core/doc_repo.py", line 460, in load_command_line
    self.config.dump(args.output_conf_file)
  File "/home/philip/checkout/hotdoc/hotdoc/core/config.py", line 344, in dump
    conf_dir = self.__conf_dir
AttributeError: 'ConfigParser' object has no attribute '_ConfigParser__conf_dir'
```

**Comment by MathieuDuponchelle** [comment]
Thanks for reporting this, I'm working on getting full test coverage of the code base, should hopefully prevent this kind of regressions.

**Comment by thiblahute** [comment]
This fixes it: https://github.com/thiblahute/hotdoc/commit/5db7145eb3ad7f2d0875d7054a9328109efe3d5c

**Comment by MathieuDuponchelle** [comment]
Thanks :)
