### ISSUE TITLE
Formatter.format_comment() is called with strings instead of comments

### ISSUE THREAD

**Issue by ptomato** [hotdoc/hotdoc#93]
According to [formatter.py:216](https://github.com/hotdoc/hotdoc/blob/master/hotdoc/core/formatter.py#L216-L225) `format_comment()` takes a `Comment` instance, but in [tree.py:212](https://github.com/hotdoc/hotdoc/blob/master/hotdoc/core/tree.py#L212-L213) and [217](https://github.com/hotdoc/hotdoc/blob/master/hotdoc/core/tree.py#L217-L218) it's called with a string. This makes it impossible to add `Comment`s with titles and short descriptions to the database, because the formatting stage will error out.

I'm not sure of the best way to fix this, maybe `Formatter` needs to gain a `format_text()` method?

Trace:
```
Traceback (most recent call last):
  File "/home/philip/checkout/hotdoc/hotdoc/run_hotdoc.py", line 100, in run
    project.format(self.link_resolver, self.output)
  File "/home/philip/checkout/hotdoc/hotdoc/core/project.py", line 202, in format
    self.tree.format(link_resolver, output, self.extensions)
  File "/home/philip/checkout/hotdoc/hotdoc/core/tree.py", line 670, in format
    self.format_page(page, link_resolver, output, extensions)
  File "/home/philip/checkout/hotdoc/hotdoc/core/tree.py", line 655, in format_page
    extension.format_page(page, link_resolver, output)
  File "/home/philip/checkout/hotdoc/hotdoc/core/extension.py", line 458, in format_page
    page.format(self.formatter, link_resolver, output, actual_output)
  File "/home/philip/checkout/hotdoc/hotdoc/core/tree.py", line 264, in format
    self.__format_page_comment(formatter, link_resolver)
  File "/home/philip/checkout/hotdoc/hotdoc/core/tree.py", line 213, in __format_page_comment
    self.comment.short_description, link_resolver).strip()
  File "/home/philip/checkout/hotdoc/hotdoc/core/formatter.py", line 227, in format_comment
    return self._format_comment(comment, link_resolver)
  File "/home/philip/checkout/hotdoc/hotdoc/core/formatter.py", line 855, in _format_comment
    comment, link_resolver)
  File "/home/philip/checkout/hotdoc/hotdoc/parsers/gtk_doc.py", line 455, in translate_comment
    self.translate_tags(comment, link_resolver)
  File "/home/philip/checkout/hotdoc/hotdoc/parsers/gtk_doc.py", line 464, in translate_tags
    tag = comment.tags.get(tname)
AttributeError: 'str' object has no attribute 'tags'
```

**Comment by ptomato** [comment]
`Comment.title` and `Comment.short_description` are actually supposed to be separate `Comment` instances. This can be closed, I'll open a pull request later to clarify this in the docstrings.
